### ISSUE TITLE
Specifying classes.txt which is not on the same path as all images results in an error

### ISSUE THREAD

**Issue by MrFresh1** [HumanSignal/labelImg#530]
- **OS: Lubuntu 18.10**
- **PyQt version: 5.10**

Hi, I am on the current most recent commit 731735f187ca23b02be685421d2730bea1b4cc52 and found the following issue. Starting labelImg like so:
`./labelImg.py /home/uni/git/trafficsign_detection/images_test/ ../trafficsign_detection/images/classes.txt`
I get the following error:

> Traceback (most recent call last):
  File "./labelImg.py", line 1483, in <module>
    sys.exit(main())
  File "./labelImg.py", line 1479, in main
    app, _win = get_main_app(sys.argv)
  File "./labelImg.py", line 1472, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "./labelImg.py", line 477, in __init__
    self.openDirDialog(dirpath=self.filePath, silent=True)
  File "./labelImg.py", line 1189, in openDirDialog
    self.importDirImages(targetDirPath)
  File "./labelImg.py", line 1200, in importDirImages
    self.openNextImg()
  File "./labelImg.py", line 1273, in openNextImg
    self.loadFile(filename)
  File "./labelImg.py", line 1037, in loadFile
    self.loadYOLOTXTByFilename(txtPath)
  File "./labelImg.py", line 1433, in loadYOLOTXTByFilename
    tYoloParseReader = YoloReader(txtPath, self.image)
  File "/home/uni/git/labelImg/libs/yolo_io.py", line 100, in __init__
    classesFile = open(self.classListPath, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/uni/git/trafficsign_detection/images_test/classes.txt'

Specifying a path to classes.txt which is not in the same folder as the images results in the error.

I was able to solve this problem by using the third input argument of _YoloReader_ which is currently not being used:
https://github.com/tzutalin/labelImg/blob/master/labelImg.py#L1432

This way _classListPath_ of class _YoloReader_ is not always _None_. I used _defaultPrefdefClassFile_ of class _MainWindow_ as the third input argument.

**Comment by HitPant** [comment]
Can you specify where exactly you made changes.

**Comment by MrFresh1** [comment]
Hi HitPant,

I guess should have linked the commit at the time instead of the master branch for that file, so here we go:
[https://github.com/HumanSignal/labelImg/blob/731735f187ca23b02be685421d2730bea1b4cc52/labelImg.py#L1432](https://github.com/HumanSignal/labelImg/blob/731735f187ca23b02be685421d2730bea1b4cc52/labelImg.py#L1432)

This was some time ago and I tried to understand what I did back then and it seems I just added a third input argument to running labelImg.py. Unfortunately I cannot tell you more than that. Just try out a few things. If the error still persists for you, just move the classes.txt into the same directory as the images.
